#!/usr/bin/env bash
# Register a NEW AiAgentSender as an FCC extension.
# Writes ONLY fce-ai-agent/config/extension.env.
#
# Usage:
#   ./scripts/pre-register.sh 0x<AiAgentSender>
#   INSTRUCTION_SENDER=0x... ./scripts/pre-register.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$PROJECT_DIR/.." && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[pre-register]${NC} $*"; }
die()  { echo -e "${RED}[pre-register] ERROR:${NC} $*" >&2; exit 1; }

# shellcheck source=lib/guard.sh
source "$SCRIPT_DIR/lib/guard.sh"
assert_ai_agent_project "$PROJECT_DIR"

if [[ -f "$PROJECT_DIR/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "$PROJECT_DIR/.env"
    set +a
fi

INSTRUCTION_SENDER="${1:-${INSTRUCTION_SENDER:-}}"
[[ -n "$INSTRUCTION_SENDER" ]] || die "pass AiAgentSender address: ./scripts/pre-register.sh 0x..."
assert_not_matching_sender "$INSTRUCTION_SENDER"
[[ "$INSTRUCTION_SENDER" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "invalid address: $INSTRUCTION_SENDER"

CHAIN_URL="${CHAIN_URL:-https://coston2-api.flare.network/ext/C/rpc}"
ADDRESSES_FILE="${ADDRESSES_FILE:-$PROJECT_DIR/config/coston2/deployed-addresses.json}"
if [[ "$ADDRESSES_FILE" != /* ]]; then
    ADDRESSES_FILE="$PROJECT_DIR/$ADDRESSES_FILE"
fi
[[ -f "$ADDRESSES_FILE" ]] || die "addresses file not found: $ADDRESSES_FILE"

CONFIG_OUTPUT="$PROJECT_DIR/config/extension.env"
assert_not_matching_path "$CONFIG_OUTPUT"

TOOLS_DIR="${FCC_TOOLS_DIR:-$REPO_ROOT/fce-matching-engine/tools}"
[[ -d "$TOOLS_DIR" ]] || die "FCC tools not found at $TOOLS_DIR"

MATCHING_ENV="$REPO_ROOT/fce-matching-engine/config/extension.env"
if [[ -f "$MATCHING_ENV" ]]; then
    log "Matching extension.env exists — will not read or write it."
fi

[[ -n "${DEPLOYMENT_PRIVATE_KEY:-}" ]] || die "DEPLOYMENT_PRIVATE_KEY not set (put it in fce-ai-agent/.env)"

log "Chain URL:      $CHAIN_URL"
log "Sender:         $INSTRUCTION_SENDER"
log "Tools (read):   $TOOLS_DIR"
log "Write config:   $CONFIG_OUTPUT"

cd "$TOOLS_DIR"
LOG_FILE="$PROJECT_DIR/config/deploy.log"
assert_not_matching_path "$LOG_FILE"
mkdir -p "$(dirname "$LOG_FILE")"

EXTENSION_ID=$(go run ./cmd/register-extension \
    -a "$ADDRESSES_FILE" \
    -c "$CHAIN_URL" \
    --instructionSender "$INSTRUCTION_SENDER" 2>"$LOG_FILE" | tail -1) || {
    echo -e "${RED}Registration failed. Logs:${NC}" >&2
    cat "$LOG_FILE" >&2
    die "register-extension failed"
}

[[ "$EXTENSION_ID" =~ ^0x[0-9a-fA-F]{64}$ ]] || {
    echo -e "${RED}register-extension output was not a valid ID. Logs:${NC}" >&2
    cat "$LOG_FILE" >&2
    die "invalid EXTENSION_ID: '$EXTENSION_ID'"
}
assert_not_matching_extension "$EXTENSION_ID"

cat > "$CONFIG_OUTPUT" <<EOF
# Auto-generated by fce-ai-agent/scripts/pre-register.sh — do not copy to matching-engine
EXTENSION_ID=$EXTENSION_ID
INSTRUCTION_SENDER=$INSTRUCTION_SENDER
EOF

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN} AI-agent pre-register complete${NC}"
echo -e "${GREEN}========================================${NC}"
echo "  EXTENSION_ID         $EXTENSION_ID"
echo "  INSTRUCTION_SENDER   $INSTRUCTION_SENDER"
echo "  Config file          $CONFIG_OUTPUT"
echo ""
echo "  Confirm EXTENSION_ID is NOT 0x...1028b (matching)."
echo "  Next: ./scripts/start-services.sh --chain coston2 --tunnel"
